"""removed unique url

Revision ID: e5c43fde0dcd
Revises: 69c62b7088dc
Create Date: 2025-12-10 12:33:19.623770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c43fde0dcd'
down_revision: Union[str, None] = '69c62b7088dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scans_url_key'), 'scans', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('scans_url_key'), 'scans', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
